name: deno-ci

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@master
        with:
          deno-version: 1.6.0
      - run: deno --version
      - run: deno fmt --check

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v') && github.repository == 'ts-graphviz/deno'
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
