name: Publish Egg

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish-egg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@master
        with:
          deno-version: 1.6.0
      - run: deno install -Afq --unstable https://x.nest.land/eggs@0.3.4/eggs.ts
      - run: |
          export PATH="/home/runner/.deno/bin:$PATH"
          eggs link ${{ secrets.NEST_API_KEY }}
          eggs publish
