name: Publish Egg

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-egg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@master
        with:
          deno-version: 1.1.1
      - run: deno install -A -f --unstable -n eggs https://x.nest.land/eggs@0.1.4/mod.ts
      - run: |
          export PATH="/home/runner/.deno/bin:$PATH"
          eggs link --key ${{ secrets.NEST_API_KEY }}
          eggs publish
